{% set version = "0.2" %}

package:
  name: mpld3
  version: {{ version }}

source:
  fn: mpld3-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/m/mpld3/mpld3-{{ version }}.tar.gz
  sha256: 6388fec56a683991b8f4b7ddb8b7c8c06cddb25491a0b503eef9a028ac16fa78

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - mplexporter
  run:
    - python
    - jinja2
    - matplotlib
    - mplexporter

test:
  imports:
    - mpld3

about:
  home: http://mpld3.github.com
  license: BSD 3-Clause
  summary: 'D3 Viewer for Matplotlib.'

extra:
  recipe-maintainers:
    - jakevdp
    - ocefpaf
