{% set version = "0.2" %}

package:
  name: mpld3
  version: {{ version }}

source:
  fn: mpld3-{{ version }}.tar.gz
  url: https://github.com/mpld3/mpld3/archive/v{{ version }}.tar.gz
  sha256: 4c7e875548ef57a01e04fd6ef4405f08ecde47521fbc6692fcf4900e91c2c0b8

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - mplexporter
  run:
    - python
    - jinja2
    - matplotlib
    - mplexporter

test:
  imports:
    - mpld3

about:
  home: http://mpld3.github.com
  license: BSD 3-Clause
  summary: 'D3 Viewer for Matplotlib.'

extra:
  recipe-maintainers:
    - jakevdp
    - ocefpaf
