{% set name = "mpld3" %}
{% set version = "0.5.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mpld3-{{ version }}.tar.gz
  sha256: bffe2c93f8b406f8d4dc059565dfecb4779e8a1fc50bfbb4e7f5d476a274eab7

build:
  number: 0
  script: pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - jinja2
    - matplotlib-base

test:
  imports:
    - mpld3
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://mpld3.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: D3 Viewer for Matplotlib.
  doc_url: https://mpld3.github.io/
  dev_url: https://github.com/mpld3/mpld3

extra:
  recipe-maintainers:
    - etgalloway
    - jakevdp
    - ocefpaf
