{% set name = "mpld3" %}
{% set version = "0.5.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mpld3-{{ version }}.tar.gz
  sha256: d8d228b2911132fd0154e2a49543b7f97247f9851cfe468c6b616f452c676158

build:
  number: 0
  script: pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - jinja2
    - matplotlib-base

test:
  imports:
    - mpld3
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://mpld3.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'D3 Viewer for Matplotlib.'
  doc_url: https://mpld3.github.io/
  dev_url: https://github.com/mpld3/mpld3

extra:
  recipe-maintainers:
    - etgalloway
    - jakevdp
    - ocefpaf
