{% set version = "0.5.5" %}

package:
  name: mpld3
  version: {{ version }}

source:
  fn: mpld3-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/m/mpld3/mpld3-{{ version }}.tar.gz
  sha256: b080f3535238a71024c0158280ab4f6091717c45347c41c907012f8dd6da1bd5

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - jinja2 >=2.7
    - matplotlib >=1.3
    # Optionally, and preferably IPython 2.0+, see https://mpld3.github.io/install.html
    - ipython >=2.0

test:
  imports:
    - mpld3
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://mpld3.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'D3 Viewer for Matplotlib.'
  doc_url: https://mpld3.github.io/
  dev_url: https://github.com/mpld3/mpld3

extra:
  recipe-maintainers:
    - etgalloway
    - jakevdp
    - ocefpaf
