{% set version = "0.5.2" %}

package:
  name: mpld3
  version: {{ version }}

source:
  fn: mpld3-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/m/mpld3/mpld3-{{ version }}.tar.gz
  sha256: 1be25e908eb2abea89169b1c532f0d628dba4fc41d5886a24c96f1a3971310b4

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - jinja2
    - matplotlib

test:
  imports:
    - mpld3

about:
  home: http://mpld3.github.com
  license: BSD 3-Clause
  license_family: BSD
  summary: 'D3 Viewer for Matplotlib.'

extra:
  recipe-maintainers:
    - etgalloway
    - jakevdp
    - ocefpaf
