# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "JOx35+uC4I+UcDGp0DVcVJiowR62A7kK/wT7BpRRrJ3ZL5SUOrRzcn4R2F4kggXiHSEozjsAMx0LrQ5Z9UhZcSFfLaZsXPoF7aUQjwAMkJg72tIbWKm2/03l0C8Zer/WvEzaNBKvD5suXi+hZyps6LWrdNo1AS7pm1Wq3td2wHoEF1lJnC6dS4ko6Tb5Fm5hbenOMkBEeBiNCUEeXh5lOz2CjkuKUwZ/bEvMCX5A8duyCHcsM4NIYek29kCAJS+EchsxI5fgwXw2+DEaknO57E63/4SW2Y17ai0kUSErX6f/nfhzfDQDxW5otfKKJeZvHPnW6tOiZGuU3AW4aDGJaxLQFLdDtoFn/EoZYQkGiUv1NTDgAjCAKv9/GyQ5R60XHFgigEBlZ7Inziyoe/qnVHXxgwJztTdWAVySAlJL2ZaFKw/xDYHmVcGapjXDISdXmIVIGKikLseZlIzFhydQvnp3USpdBSIKN9W3p3tRt0ldbWFJTHpfgzCEvsFWjKM3/VHcwNg4S4yfnViSBeJLasQlRKE+wrXZ/FRBP0Lcw8i8oC6VOdxadeClCYOpk/vDuRvUdvaR4JS6vOiV8VLdagJQXfyhnm+k8EJGJb5/7WS71/XL2pn4eR+Kd8SWYl+fFTkzqhK0m/4mrvhZFB0I4czby9MUHqDqmnKWqRNGbds="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
