travis:
  secure:
    BINSTAR_TOKEN: JOx35+uC4I+UcDGp0DVcVJiowR62A7kK/wT7BpRRrJ3ZL5SUOrRzcn4R2F4kggXiHSEozjsAMx0LrQ5Z9UhZcSFfLaZsXPoF7aUQjwAMkJg72tIbWKm2/03l0C8Zer/WvEzaNBKvD5suXi+hZyps6LWrdNo1AS7pm1Wq3td2wHoEF1lJnC6dS4ko6Tb5Fm5hbenOMkBEeBiNCUEeXh5lOz2CjkuKUwZ/bEvMCX5A8duyCHcsM4NIYek29kCAJS+EchsxI5fgwXw2+DEaknO57E63/4SW2Y17ai0kUSErX6f/nfhzfDQDxW5otfKKJeZvHPnW6tOiZGuU3AW4aDGJaxLQFLdDtoFn/EoZYQkGiUv1NTDgAjCAKv9/GyQ5R60XHFgigEBlZ7Inziyoe/qnVHXxgwJztTdWAVySAlJL2ZaFKw/xDYHmVcGapjXDISdXmIVIGKikLseZlIzFhydQvnp3USpdBSIKN9W3p3tRt0ldbWFJTHpfgzCEvsFWjKM3/VHcwNg4S4yfnViSBeJLasQlRKE+wrXZ/FRBP0Lcw8i8oC6VOdxadeClCYOpk/vDuRvUdvaR4JS6vOiV8VLdagJQXfyhnm+k8EJGJb5/7WS71/XL2pn4eR+Kd8SWYl+fFTkzqhK0m/4mrvhZFB0I4czby9MUHqDqmnKWqRNGbds=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
