travis:
  secure:
    BINSTAR_TOKEN: 24KTtTmPvcv5NR8ojmnW15ppRWOLiny/30i+r0fNtQguaxoHWjzdjb+NJAHANa2Ql2WUas95NTj0RXV0NRHnnbe3yUuIZeKN+ayndHV2uEjHNgIMAD+xGrMTtAWrMAAxqD4ZPWbuI5QYBU+7jtC0HCHYdG276CC/9ET7lpRMDncT3OHfzvM5Wk8uJ14i+aF0R+2EgWwGuROhIZKinFcvvC6rS4G+kdUzBqte+QmMok6ZYqnr4OgpZ293OaySBKfh6QUKBrKlcLEJqd6OBxUUGagbj+2QNsEqQz4uoL+r+TVro1utaujfLo7UqwOPjG3sE6DzsF1aVicet87p381YBB6VVx/5J6cm/e/Vb1TltAO7A3ncDC3/MsABrW2qQhiXRZ4zF84wbMwYWHtZ//ZDMoWTE7c+eBLDAFeL5MOnyIIsODIv3MmbL6b2l6u8yquEb1ita/U8T8KgBw2uAynIB5wJ41Tn7kSysTdEDDezCmOcMtl0zU7Shz1SDbZYEuvhmYIALAncoqhfYsdCfBZzr8HF8dvLxJOj8bsC+N6b8+tdl9ruOF1eKxxRgeImssDDBKmvna9QUm75v0+DyG1KgTqGNktK/kV11mzrRJp79lTM2dIurwvntLyzL1PrMK1BE0jl5McWZu9FeH9l1VVe8wEoDJgc7qd1AnOGhceXpwI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
